export const API_REQUEST_BEGIN = 'API_REQUEST_BEGIN'
export const API_REQUEST_END = 'API_REQUEST_END'
export const API_REQUEST_ERROR = 'API_REQUEST_ERROR'
export const API_REQUEST_LOG = 'API_REQUEST_LOG'

export const SEARCH_SLUG = 'SEARCH_SLUG'
export const RETRIVED_SLUG = 'RETRIVED_SLUG'